export const CREATE_BOOK_REQUEST="CREATE_BOOK_REQUEST"
export const CREATE_BOOK_SUCCESS="CREATE_BOOK_SUCCESS"
export const CREATE_BOOK_FAILURE="CREATE_BOOK_FAILURE"


export const DELETE_BOOK_REQUEST="DELETE_BOOK_REQUEST"
export const DELETE_BOOK_SUCCESS="DELETE_BOOK_SUCCESS"
export const DELETE_BOOK_FAILURE="DELETE_BOOK_FAILURE"


export const GET_ALL_BOOK_REQUEST="GET_ALL_BOOK_REQUEST"
export const GET_ALL_BOOK_SUCCESS="GET_ALL_BOOK_SUCCESS"
export const GET_ALL_BOOK_FAILURE="GET_ALL_BOOK_FAILURE"

export const BORROW_BOOK_REQUEST="BORROW_BOOK_REQUEST"
export const BORROW_BOOK_SUCCESS="BORROW_BOOK_SUCCESS"
export const BORROW_BOOK_FAILURE="BORROW_BOOK_FAILURE"

export const RETURN_BOOK_REQUEST="RETURN_BOOK_REQUEST"
export const RETURN_BOOK_SUCCESS="RETURN_BOOK_SUCCESS"
export const RETURN_BOOK_FAILURE="RETURN_BOOK_FAILURE"


export const GET_AVAILABLE_BOOK_REQUEST="GET_AVAILABLE_BOOK_REQUEST"
export const GET_AVAILABLE_BOOK_SUCCESS="GET_AVAILABLE_BOOK_SUCCESS"
export const GET_AVAILABLE_BOOK_FAILURE="GET_AVAILABLE_BOOK_FAILURE"


export const GET_USERS_ALL_BOOK_SUCCESS="GET_USERS_ALLBOOK_SUCCESS"
export const GET_USERS_ALL_BOOK_REQUEST="GET_USERS_ALL_BOOK_REQUEST"
export const GET_USERS_ALL_BOOK_FAILURE="GET_USERS_ALL_BOOK_FAILURE"

export const GET_LIKED_BOOK_REQUEST="GET_LIKED_BOOK_REQUEST"
export const GET_LIKED_BOOK_SUCCESS="GET_LIKED_BOOK_SUCCESS"
export const GET_LIKED_BOOK_FAILURE="GET_LIKED_BOOK_FAILURE"

export const LIKE_BOOK_REQUEST="LIKE_BOOK_REQUEST"
export const LIKE_BOOK_SUCCESS="LIKE_BOOK_SUCCESS"
export const LIKE_BOOK_FAILURE="LIKE_BOOK_FAILURE"


export const FIND_BOOK_BY_CONTENT_REQUEST="FIND_BOOK_BY_CONTENT_REQUEST"
export const FIND_BOOK_BY_CONTENT_SUCCESS="FIND_BOOK_BY_CONTENT_SUCCESS"
export const FIND_BOOK_BY_CONTENT_FAILURE="FIND_BOOK_BY_CONTENT_FAILURE"

export const FIND_BOOK_BY_ID_REQUEST="FIND_BOOK_BY_ID_REQUEST"
export const FIND_BOOK_BY_ID_SUCCESS="FIND_BOOK_BY_ID_SUCCESS"
export const FIND_BOOK_BY_ID_FAILURE="FIND_BOOK_BY_ID_FAILURE"


export const COMMENT_BOOK_REQUEST="COMMENT_BOOK_REQUEST"
export const COMMENT_BOOK_SUCCESS="COMMENT_BOOK_SUCCESS"
export const COMMENT_BOOK_FAILURE="COMMENT_BOOK_FAILURE"

export const SUGGESTIONS_REQUEST="SUGGESTIONS_REQUEST"
export const SUGGESTIONS_SUCCESS="SUGGESTIONS_SUCCESS"
export const SUGGESTIONS_FAILURE="SUGGESTIONS_FAILURE"